# Generated by Django 2.2.3 on 2019-08-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_1080p',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_720p',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
