# Generated by Django 2.2.3 on 2019-08-02 09:21

from django.db import migrations, models
import vodapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('vodapi', '0002_auto_20190802_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default=1, upload_to=vodapi.models.Video.upload_video_dir),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='file_1080p',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_720p',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
